name: motionclone
channels:
  - pytorch
  - nvidia
dependencies:
  - python=3.11.3
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.8
  - pip
  - pip:
    - accelerate
    - diffusers==0.16.0
    - transformers==4.28.1
    - xformers==0.0.20
    - imageio[ffmpeg]
    - decord==0.6.0
    - gdown
    - einops
    - omegaconf
    - safetensors
    - gradio
    - wandb
    - triton
    - opencv-python