name: reframing
channels:
  - defaults
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pillow
  - tqdm
  - jinja2
  - requests
  - networkx
  - sympy
  - ffmpeg
  - opencv-python
  - pytorch
  - torchvision
  - pytorch-cuda=11.8  
  - pip:
      - accelerate
      - diffusers==0.19.0
      - transformers==4.28.0
      - datasets
      - decord
      - einops
      - gradio
      - moviepy
      - safetensors
      - sentencepiece
      - timm
      - xformers
      - openai-clip
      - ftfy
      - wandb
      - fastapi
      - uvicorn
      - pyyaml
      - python-dotenv
      - huggingface-hub==0.23.0
