  motion_module:    "models/Motion_Module/v3_sd15_mm.ckpt"
  dreambooth_path: "models/DreamBooth_LoRA/realisticVisionV60B1_v51VAE.safetensors"

  temp_guidance:
    blocks:
      ['up_blocks.1', 'up_blocks.2'] 

  W: 320
  H: 320
  L: 16

  model_config: "configs/model_config/model_config.yaml"
  cfg_scale: 7.5 
  negative_prompt: "couch, sofa, ugly, deformed, noisy, blurry, distorted"

  num_inference_step: 300 
  guidance_step: 90 
  grad_guidance_scale: 1.0 
  grad_guidance_threshold: null
  
  video_path: 'resources/retriever.mp4'
  inversion_prompt: "Retriever, moves its head, on the couch" 
  new_prompt : "Lion, moves its head, in the wild, 8k, high detailed, best quality"  